### ISSUE TITLE
Doesnt work for mac64 [system]

### ISSUE THREAD

**Issue by warchiefmarkus** [User344/eac-extractor#1]
Hello, it doesnt work for [system] - mac64 - just download loader and then error. I run extractor from windows 11. If i build and run sources udner mac os will it work for mac64 payload ?

**Comment by imunproductive** [comment]
Hey! Unfortunately Windows is the only supported platform since EAC's loader binary is packed and unpacking is required before processing so i load it using LoadLibrary WinAPI. Theoretically you can emulate unpacking using something like QEMU but i didn't bother adding that.
